import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DUY THAI - Front-end Developer',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../images/me.jpg" sizes="32x32"/>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}